-- liquibase formatted sql

-- changeset chakib:009-add-reviews
ALTER TABLE product ADD COLUMN rating DOUBLE PRECISION;
ALTER TABLE product ADD COLUMN review_count INTEGER;

CREATE TABLE review (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 100) PRIMARY KEY,
    uuid UUID,
    product_id UUID NOT NULL,
    reviewer VARCHAR(255) NOT NULL,
    stars INTEGER NOT NULL,
    text VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_review_product_reviewer UNIQUE (product_id, reviewer)
);
CREATE INDEX idx_review_uuid ON review(uuid);
