quarkus.http.port=8080
quarkus.application.name=price-service
## JSON config — snake_case + null omission via CustomJsonbConfigCustomizer

## Products Api endpoint conf
the.chak.ecommerce.products.boundary.ProductsApi/mp-rest/url=http://api-gateway:8080/api
## Kafka
%dev.kafka.bootstrap.servers=localhost:9092
mp.messaging.outgoing.price-changed.connector=smallrye-kafka
mp.messaging.outgoing.price-changed.topic=price-changed
mp.messaging.outgoing.price-changed.value.serializer=io.quarkus.kafka.client.serialization.JsonbSerializer