# Configuration file
# key = value

# JSON config
quarkus.jackson.property-naming-strategy=SNAKE_CASE
quarkus.jackson.serialization-inclusion=NON_NULL
quarkus.jackson.write-dates-as-timestamps=false
quarkus.jackson.fail-on-unknown-properties=false
