# Configuration file
# key = value
#quarkus.http.cors=true
quarkus.application.name=products-service
quarkus.http.port=8080


# postgres datasource
quarkus.datasource.db-kind = postgresql
quarkus.datasource.jdbc.acquisition-timeout=PT300S
quarkus.datasource.jdbc.url = jdbc:postgresql://postgres:5432/products
quarkus.hibernate-orm.physical-naming-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy


# Liquibase minimal config properties
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.change-log=db/changelog/db.changelog-master.xml

# Kafka configuration
%dev.kafka.bootstrap.servers=localhost:9092
mp.messaging.incoming.price-changed.connector=smallrye-kafka
mp.messaging.incoming.price-changed.topic=price-changed
mp.messaging.incoming.price-changed.value.deserializer=io.quarkus.kafka.client.serialization.JsonbDeserializer

mp.messaging.outgoing.product-updated.connector=smallrye-kafka
mp.messaging.outgoing.product-updated.topic=product-updated
mp.messaging.outgoing.product-updated.value.serializer=io.quarkus.kafka.client.serialization.JsonbSerializer
mp.messaging.outgoing.product-deleted.connector=smallrye-kafka
mp.messaging.outgoing.product-deleted.topic=product-deleted
mp.messaging.outgoing.product-deleted.value.serializer=io.quarkus.kafka.client.serialization.JsonbSerializer

# MinIO Configuration
products.minio.endpoint=http://minio:9000
products.minio.region=us-east-1
products.minio.access-key=minioadmin
products.minio.secret-key=minioadmin

products.images.bucket=product-images

# JSON config
quarkus.jsonb.property-naming-strategy=LOWER_CASE_WITH_UNDERSCORES
