quarkus.http.port=8082

quarkus.datasource.username = postgres
quarkus.datasource.password = postgres
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/products
# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation = validate
quarkus.hibernate-orm.log.sql=true

quarkus.devservices.enabled=false
mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:29092

quarkus.s3.endpoint-override=http://localhost:9000