quarkus.http.port=8086
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/analytics
quarkus.hibernate-orm.database.generation=validate
quarkus.hibernate-orm.log.sql=true
quarkus.devservices.enabled=false
mp.messaging.connector.smallrye-kafka.bootstrap.servers=localhost:29092
