-- liquibase formatted sql

-- changeset chakib:001-init-schema
CREATE TABLE dim_product (
    product_id         VARCHAR(255) NOT NULL,
    title              VARCHAR(255),
    category_id        BIGINT,
    category_label     VARCHAR(255),
    subcategory_id     BIGINT,
    subcategory_label  VARCHAR(255),
    deleted            BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_dim_product PRIMARY KEY (product_id)
);

CREATE TABLE fact_sales_line (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    order_id        VARCHAR(255) NOT NULL,
    product_id      VARCHAR(255) NOT NULL,
    product_title   VARCHAR(255),
    units           INTEGER      NOT NULL,
    unit_price      DOUBLE PRECISION NOT NULL,
    percentage_off  DOUBLE PRECISION,
    line_revenue    DOUBLE PRECISION NOT NULL,
    order_date      TIMESTAMP    NOT NULL,
    order_month     VARCHAR(7)   NOT NULL,
    user_id         VARCHAR(255),
    CONSTRAINT pk_fact_sales_line PRIMARY KEY (id),
    CONSTRAINT uk_fact_sales_line_order_product UNIQUE (order_id, product_id)
);

-- The dashboard rolls up by month, by product, and joins to the dimension by product.
CREATE INDEX idx_fact_sales_line_order_month ON fact_sales_line (order_month);
CREATE INDEX idx_fact_sales_line_product_id ON fact_sales_line (product_id);
CREATE INDEX idx_fact_sales_line_order_id ON fact_sales_line (order_id);
