server:
  port: 8080

spring:
  profiles:
    active: dev

  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/api/products/**,/api/categories/**,/api/promotions/**
          filters:
            - StripPrefix=1
        - id: orders-service
          uri: lb://orders-service
          predicates:
            - Path=/api/orders/**
          filters:
            - StripPrefix=1
        - id: authentication-service
          uri: lb://authenticate-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: payments-service
          uri: lb://payments-service
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1
logging:
  level:
    org.springframework.security: debug
---
spring:
  profiles: docker
cors:
  allowedOrigins: http://localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
