apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-eureka-server
  labels:
    app: ecommerce-eureka-server
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-eureka-server
      version: v1
  template:
    metadata:
      labels:
        app: ecommerce-eureka-server
        version: v1
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: -Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:///dev/./urandom
          image: ecommerce/ecommerce-eureka-server
          command:
            [
              "java",
              "-XX:+UnlockExperimentalVMOptions",
              "-XX:+UseCGroupMemoryLimitForHeap",
              "-Djava.security.egd=file:/dev/./urandom",
              "-jar",
              "/app.jar",
            ]
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet: # make an HTTP request
              port: 8761 # port to use
              path: /actuator/health # endpoint to hit
              scheme: HTTP # or HTTPS
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 1
          name: ecommerce-eureka-server
          ports:
            - containerPort: 8761
              name: http
              protocol: TCP
          readinessProbe:
            httpGet: # make an HTTP request
              port: 8761 # port to use
              path: /actuator/health # endpoint to hit
              scheme: HTTP # or HTTPS
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  labels:
    app: ecommerce-eureka-server
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8761
  selector:
    app: ecommerce-eureka-server
