apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend
  labels:
    app: ecommerce-frontend
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-frontend
      version: v1
  template:
    metadata:
      labels:
        app: ecommerce-frontend
        version: v1
    spec:
      containers:
        - env:
          image: ecommerce_ecommerce-front
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet: # make an HTTP request
              port: 80 # port to use
              path: / # endpoint to hit
              scheme: HTTP # or HTTPS
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 1
          name: ecommerce-frontend
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          readinessProbe:
            httpGet: # make an HTTP request
              port: 80 # port to use
              path: / # endpoint to hit
              scheme: HTTP # or HTTPS
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-frontend
  labels:
    app: ecommerce-frontend
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  selector:
    app: ecommerce-frontend
