apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-user-service
  labels:
    app: ecommerce-user-service
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-user-service
      version: v1
  template:
    metadata:
      labels:
        app: ecommerce-user-service
        version: v1
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: -Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:///dev/./urandom
          image: ecommerce_ecommerce-user-service
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet: # make an HTTP request
              port: 8082 # port to use
              path: /info/health # endpoint to hit
              scheme: HTTP # or HTTPS
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 1
          name: ecommerce-user-service
          ports:
            - containerPort: 8082
              name: http
              protocol: TCP
          readinessProbe:
            httpGet: # make an HTTP request
              port: 8082 # port to use
              path: /info/health # endpoint to hit
              scheme: HTTP # or HTTPS
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: ecommerce-user-service
  labels:
    app: ecommerce-user-service
spec:
  ports:
  - name: http
    port: 8082
  selector:
    app: ecommerce-user-service
